version: '3.8'

services:  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  manager:
    build:
      context: manager
      dockerfile: Dockerfile
    container_name: manager
    ports:
      - "5555:5555"
    environment:
      - PORT_GATEWAY=5555
      - PORT_HANDLER=8080
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
          condition: service_healthy

  accessor:
    build:
      context: accessor
      dockerfile: Dockerfile
    container_name: accessor
    ports:
      - "8080:8080"
    environment:
      - DATABASEURL=${DATABASEURL}
      - PORT_HANDLER=8080
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
        rabbitmq:
          condition: service_healthy

volumes:
  mongo-data: