apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendmailpubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://guest:guest@rabbitmq:5672"
scopes:
  - pnmanagermail
  - pnaccessormail